name: nutrivigil
description: Aplicación Flutter para seguimiento nutricional en paciente crítico.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  drift: ^2.21.0
  drift_sqflite: 2.0.1
  path_provider: ^2.1.2
  intl: ^0.20.2
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.3.0
  printing: ^5.12.0
  get_it: ^7.6.4
  uuid: ^4.4.0
  pdf: ^3.10.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  drift_dev: ^2.21.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo_real.png"
  min_sdk_android: 21


dependency_overrides:
  flutter_local_notifications:
    path: list/flutter_local_notifications

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
